#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-daemons
Version  : 1.2.3
Release  : 2
URL      : https://rubygems.org/downloads/daemons-1.2.3.gem
Source0  : https://rubygems.org/downloads/daemons-1.2.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
Ruby Daemons
============
Daemons provides an easy way to wrap existing ruby scripts (for example a self-written server)
to be _run as a daemon_ and to be _controlled by simple start/stop/restart commands_.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n daemons-1.2.3
gem spec %{SOURCE0} -l --ruby > rubygem-daemons.gemspec

%build
gem build rubygem-daemons.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
daemons-1.2.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/daemons-1.2.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/CurrentProcess/cdesc-CurrentProcess.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/CurrentProcess/change_privilege-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/call_as_daemon-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/call_as_daemon-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/cdesc-Daemonize.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/close_io-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/close_io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/daemonize-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/daemonize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/redirect_io-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/redirect_io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/safefork-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/safefork-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/simulate-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemonize/simulate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/app_argv-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/cdesc-Application.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/change_privilege-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/controller_argv-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/default_show_status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/exception_log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/group-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/logdir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/logfile-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/logfilename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/output_logfile-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/output_logfilename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/pid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/pidfile_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/reload-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/running%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/script-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/show_status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/show_status_callback%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/start_exec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/start_load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/start_none-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/start_proc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/started-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/zap%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Application/zap-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/app_argv-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/app_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/applications-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/cdesc-ApplicationGroup.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/controller_argv-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/create_monitor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/dir_mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/find_applications-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/find_applications_by_app_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/find_applications_by_pidfiles-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/monitor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/multiple-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/new_application-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/pidfile_dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/reload_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/running%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/script-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/setup_app-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/show_status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/start_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/stop_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/ApplicationGroup/zap_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/CmdException/cdesc-CmdException.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Controller/app_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Controller/catch_exceptions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Controller/cdesc-Controller.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Controller/group-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Controller/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Controller/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Controller/print_usage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Controller/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Controller/setup_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Controller/split_argv-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Exception/cdesc-Exception.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Monitor/cdesc-Monitor.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Monitor/find-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Monitor/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Monitor/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Monitor/start_with_pidfile-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Monitor/start_without_pidfile-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Monitor/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Monitor/watch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Optparse/cdesc-Optparse.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Optparse/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Optparse/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Optparse/usage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Pid/cdesc-Pid.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Pid/cleanup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Pid/dir-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Pid/exist%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Pid/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Pid/pid%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Pid/pid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Pid/running%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Pid/running%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/Pid/zap-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/cdesc-PidFile.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/cleanup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/exist%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/existing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/filename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/find_files-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/multiple-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/number-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/pid%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/pid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/progname-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidFile/zap-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidMem/cdesc-PidMem.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidMem/existing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/PidMem/pid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/RuntimeException/cdesc-RuntimeException.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/SystemError/cdesc-SystemError.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/SystemError/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/SystemError/system_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/TimeoutError/cdesc-TimeoutError.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/call-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/cdesc-Daemons.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/controller-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/controller-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/daemonize-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/daemonize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/group-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/group-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/run-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/run_proc-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Daemons/run_proc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Object/groupname-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/Object/username-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/daemons-1.2.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/Releases
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/call/call.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/call/call_monitor.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/daemonize/daemonize.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_crash.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_custom_logfiles.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_exec.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_exit.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_hanging.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_keep_pid_files.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_monitor.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_monitor_multiple.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_monitor_nocrash.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_multiple.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_normal.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_ontop.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_optionparser.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_proc.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_proc_multiple.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_proc_rand.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_proc_simple.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/ctrl_slowstop.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/myserver.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/myserver_crashing.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/myserver_exiting.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/myserver_hanging.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/examples/run/myserver_slowstop.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/application.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/application_group.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/change_privilege.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/cmdline.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/controller.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/daemonize.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/etc_extension.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/exceptions.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/monitor.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/pid.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/pidfile.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/pidmem.rb
/usr/lib64/ruby/gems/2.2.0/gems/daemons-1.2.3/lib/daemons/version.rb
/usr/lib64/ruby/gems/2.2.0/specifications/daemons-1.2.3.gemspec
