#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-daemons
Version  : 1.2.3
Release  : 3
URL      : https://rubygems.org/downloads/daemons-1.2.3.gem
Source0  : https://rubygems.org/downloads/daemons-1.2.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
Ruby Daemons
============
Daemons provides an easy way to wrap existing ruby scripts (for example a self-written server)
to be _run as a daemon_ and to be _controlled by simple start/stop/restart commands_.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n daemons-1.2.3
gem spec %{SOURCE0} -l --ruby > rubygem-daemons.gemspec

%build
gem build rubygem-daemons.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
daemons-1.2.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/daemons-1.2.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/README.md
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/Releases
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/call/call.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/call/call_monitor.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/daemonize/daemonize.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_crash.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_custom_logfiles.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_exec.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_exit.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_hanging.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_keep_pid_files.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_monitor.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_monitor_multiple.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_monitor_nocrash.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_multiple.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_normal.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_ontop.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_optionparser.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_proc.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_proc_multiple.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_proc_rand.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_proc_simple.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/ctrl_slowstop.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/myserver.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/myserver_crashing.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/myserver_exiting.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/myserver_hanging.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/examples/run/myserver_slowstop.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/application_group.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/change_privilege.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/cmdline.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/daemonize.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/etc_extension.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/monitor.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/pid.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/pidfile.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/pidmem.rb
/usr/lib64/ruby/gems/2.3.0/gems/daemons-1.2.3/lib/daemons/version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/daemons-1.2.3.gemspec
